# fly.toml app configuration file generated for wstlibrary on 2023-06-26T17:51:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wstlibrary"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
